# Generated by Django 4.2.13 on 2026-07-07 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sphere', models.CharField(choices=[('procurement', 'Госзакупки'), ('construction', 'Строительство'), ('agro', 'АПК/Субсидии'), ('osms', 'ОСМС'), ('subsoil', 'Недропользование'), ('budget', 'Бюджет'), ('tax', 'Налоги'), ('other', 'Иное')], max_length=20)),
                ('subject_name', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('analysis', 'Анализ'), ('prevention', 'Превенция'), ('material', 'Материал'), ('erdr', 'ЕРДР'), ('in_progress', 'В производстве'), ('completed', 'Завершено')], default='analysis', max_length=20)),
                ('level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=10)),
                ('source', models.CharField(choices=[('internal', 'Внутренний'), ('external', 'Внешний'), ('citizen', 'Обращение граждан'), ('media', 'СМИ')], default='internal', max_length=20)),
                ('detected_at', models.DateField()),
                ('year', models.IntegerField()),
                ('measures', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_materials', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='regions.district')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['district', 'year', 'level'], name='risks_riskm_distric_6d955f_idx')],
            },
        ),
    ]
