# Generated by Django 4.2.13 on 2026-07-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('employer_name', models.CharField(max_length=500)),
                ('employer_bin', models.CharField(max_length=12)),
                ('employees_count', models.IntegerField(default=0)),
                ('registered_count', models.IntegerField(default=0)),
                ('unregistered_count', models.IntegerField(default=0)),
                ('contributions', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('debt_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('registered', 'Зарегистрирован'), ('paying', 'Оплачивает'), ('debt', 'Долг'), ('exempt', 'Льгота'), ('unknown', 'Неизвестен')], default='registered', max_length=20)),
                ('risk_flag', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osms_data', to='regions.district')),
            ],
            options={
                'ordering': ['-debt_amount'],
            },
        ),
    ]
