# Generated by Django 4.2.13 on 2026-07-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsoilContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=500)),
                ('company_bin', models.CharField(max_length=12)),
                ('mineral_type', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('exploration', 'Разведка'), ('production', 'Добыча'), ('combined', 'Совмещённый')], default='production', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Действующий'), ('suspended', 'Приостановлен'), ('terminated', 'Расторгнут'), ('expired', 'Истёк')], default='active', max_length=20)),
                ('area_ha', models.FloatField(default=0)),
                ('obligations_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fulfilled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('risk_nonpayment', models.BooleanField(default=False)),
                ('risk_overextract', models.BooleanField(default=False)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsoil', to='regions.district')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
