# Generated by Django 5.0.6 on 2026-07-15 11:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тематический слой',
                'verbose_name_plural': 'Тематические слои',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kato_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='КАТО')),
                ('gadm_gid', models.CharField(max_length=40, unique=True, verbose_name='GADM GID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Наименование (лат.)')),
                ('level', models.CharField(choices=[('country', 'Страна'), ('region', 'Область'), ('district', 'Район')], db_index=True, max_length=16, verbose_name='Уровень')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Геометрия')),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Население')),
                ('area_km2', models.FloatField(blank=True, null=True, verbose_name='Площадь, км²')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='territories.territory', verbose_name='Родительская территория')),
            ],
            options={
                'verbose_name': 'Территория',
                'verbose_name_plural': 'Территории',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вес')),
                ('threshold', models.FloatField(blank=True, null=True, verbose_name='Порог')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='territories.thematiclayer', verbose_name='Слой')),
            ],
            options={
                'verbose_name': 'Индикатор риска',
                'verbose_name_plural': 'Индикаторы риска',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512, verbose_name='Файл')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('done', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('rows_ok', models.PositiveIntegerField(default=0, verbose_name='Загружено')),
                ('rows_error', models.PositiveIntegerField(default=0, verbose_name='С ошибками')),
                ('log', models.TextField(blank=True, verbose_name='Протокол')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='territories.thematiclayer', verbose_name='Слой')),
            ],
            options={
                'verbose_name': 'Загрузка данных',
                'verbose_name_plural': 'Загрузки данных',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Атрибуты')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Геометрия')),
                ('risk_score', models.FloatField(blank=True, null=True, verbose_name='Балл риска')),
                ('risk_level', models.CharField(blank=True, max_length=16, verbose_name='Уровень риска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_objects', to='territories.territory', verbose_name='Территория')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='territories.thematiclayer', verbose_name='Слой')),
            ],
            options={
                'verbose_name': 'Объект слоя',
                'verbose_name_plural': 'Объекты слоёв',
            },
        ),
    ]
