# Generated by Django 5.0.6 on 2026-07-15 13:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='ID источника')),
                ('source_system', models.CharField(blank=True, max_length=50, verbose_name='Система-источник')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата импорта')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Атрибуты')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Геометрия')),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Балл риска')),
                ('risk_level', models.CharField(blank=True, max_length=20, verbose_name='Уровень риска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Объект слоя',
                'verbose_name_plural': 'Объекты слоёв',
            },
        ),
        migrations.CreateModel(
            name='ThematicLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Наименование')),
                ('color_hex', models.CharField(blank=True, default='#3388FF', max_length=7, verbose_name='Цвет (HEX)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тематический слой',
                'verbose_name_plural': 'Тематические слои',
                'ordering': ['sort_order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_code', models.CharField(max_length=50, verbose_name='Код индикатора')),
                ('indicator_name', models.CharField(max_length=255, verbose_name='Наименование индикатора')),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Исходное значение')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Вес')),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вклад в итоговый балл')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Рассчитано')),
                ('geo_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='territories.geoobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Фактор риска',
                'verbose_name_plural': 'Факторы риска (расшифровка расчёта)',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kato_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='КАТО')),
                ('external_id', models.CharField(max_length=40, unique=True, verbose_name='ID источника')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Наименование (рус.)')),
                ('name_kz', models.CharField(blank=True, max_length=255, verbose_name='Наименование (қаз.)')),
                ('level', models.CharField(choices=[('oblast', 'Область'), ('rayon', 'Район'), ('settlement', 'Населённый пункт')], db_index=True, max_length=20, verbose_name='Уровень')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Геометрия')),
                ('population', models.BigIntegerField(blank=True, null=True, verbose_name='Население')),
                ('area_km2', models.FloatField(blank=True, null=True, verbose_name='Площадь, км²')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='territories.territory', verbose_name='Родительская территория')),
            ],
            options={
                'verbose_name': 'Территория',
                'verbose_name_plural': 'Территории',
                'ordering': ['level', 'name_ru'],
            },
        ),
        migrations.AddField(
            model_name='geoobject',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_objects', to='territories.territory', verbose_name='Территория'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Файл')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='Источник данных')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('done', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('imported_rows', models.PositiveIntegerField(default=0, verbose_name='Загружено')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='С ошибками')),
                ('error_log', models.JSONField(blank=True, default=list, verbose_name='Протокол ошибок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем загружено')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='territories.thematiclayer', verbose_name='Слой')),
            ],
            options={
                'verbose_name': 'Загрузка данных',
                'verbose_name_plural': 'Загрузки данных',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='geoobject',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='territories.thematiclayer', verbose_name='Слой'),
        ),
    ]
