# Generated by Django 5.0.6 on 2026-07-18 07:49

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0002_alter_geoobject_layer'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='geoobject',
            index=models.Index(fields=['layer', 'territory'], name='territories_layer_i_6f9a63_idx'),
        ),
        migrations.AddIndex(
            model_name='geoobject',
            index=models.Index(fields=['risk_level'], name='territories_risk_le_bc3b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='geoobject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='geoobject_attrs_gin'),
        ),
    ]
