# Generated by Django 5.0.6 on 2026-07-18 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoobject',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_objects', to='territories.thematiclayer', verbose_name='Слой'),
        ),
    ]
