# Generated by Django 4.2.13 on 2026-07-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('school', 'Школа'), ('hospital', 'Больница'), ('fap', 'ФАП'), ('culture', 'Дом культуры'), ('road', 'Дорога'), ('water', 'Водоснабжение'), ('gas', 'Газоснабжение'), ('electricity', 'Электроснабжение'), ('heat', 'Теплоснабжение'), ('social', 'Социальный объект'), ('digital', 'Цифровизация')], max_length=20)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('customer_name', models.CharField(max_length=500)),
                ('contractor_name', models.CharField(blank=True, max_length=500)),
                ('designer_name', models.CharField(blank=True, max_length=500)),
                ('design_cost', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('financing_source', models.CharField(choices=[('republican', 'Республиканский'), ('local', 'Местный'), ('mixed', 'Смешанный'), ('private', 'Частный')], default='local', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('actual_status', models.CharField(choices=[('planned', 'Планируется'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('delayed', 'Задержка'), ('suspended', 'Приостановлен')], default='in_progress', max_length=20)),
                ('readiness_pct', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=10)),
                ('overprice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_objects', to='regions.district')),
            ],
            options={
                'ordering': ['-risk_level', 'name'],
            },
        ),
    ]
