"""Начальная схема

Revision ID: d16e7f08d828
Revises: 
Create Date: 2026-07-20 22:45:59.443312
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd16e7f08d828'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boundary_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('downloaded_at', sa.Date(), nullable=True),
    sa.Column('license_name', sa.String(length=128), nullable=False),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('attribution_text', sa.Text(), nullable=False),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=False),
    sa.Column('administrative_division_as_of', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_boundary_version_code')
    )
    op.create_table('budget_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('source_parent_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('level BETWEEN 0 AND 4', name='ck_budget_program_level_range'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['parent_id'], ['budget_programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'name', 'level', name='uq_budget_program_code_name_level')
    )
    op.create_index(op.f('ix_budget_programs_import_job_id'), 'budget_programs', ['import_job_id'], unique=False)
    op.create_index('ix_budget_programs_level', 'budget_programs', ['level'], unique=False)
    op.create_index(op.f('ix_budget_programs_natural_key'), 'budget_programs', ['natural_key'], unique=False)
    op.create_index('ix_budget_programs_parent', 'budget_programs', ['parent_id'], unique=False)
    op.create_index(op.f('ix_budget_programs_source_dataset_id'), 'budget_programs', ['source_dataset_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permission_code')
    )
    op.create_table('persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('iin', sa.String(length=12), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=True),
    sa.Column('company_count', sa.Integer(), nullable=True),
    sa.Column('in_lzhepred_list', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint("iin IS NULL OR iin ~ '^[0-9]{12}$'", name='ck_person_iin_format'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iin', name='uq_person_iin')
    )
    op.create_index('ix_persons_full_name', 'persons', ['full_name'], unique=False)
    op.create_index(op.f('ix_persons_import_job_id'), 'persons', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_persons_natural_key'), 'persons', ['natural_key'], unique=False)
    op.create_index(op.f('ix_persons_source_dataset_id'), 'persons', ['source_dataset_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sensitive_data_access', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_role_code')
    )
    op.create_table('subsidy_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('animal_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_subsidy_program_code')
    )
    op.create_index('ix_subsidy_programs_animal_type', 'subsidy_programs', ['animal_type'], unique=False)
    op.create_index(op.f('ix_subsidy_programs_import_job_id'), 'subsidy_programs', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_subsidy_programs_natural_key'), 'subsidy_programs', ['natural_key'], unique=False)
    op.create_index(op.f('ix_subsidy_programs_source_dataset_id'), 'subsidy_programs', ['source_dataset_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('territories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('kato_code', sa.String(length=9), nullable=True),
    sa.Column('iso3166_2', sa.String(length=16), nullable=True),
    sa.Column('osm_relation_id', sa.Integer(), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_kk', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=24), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('boundary_version_id', sa.UUID(), nullable=False),
    sa.Column('admin_center_name', sa.String(length=255), nullable=True),
    sa.Column('area_km2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('area_km2_computed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.CheckConstraint('area_km2 IS NULL OR area_km2 > 0', name='ck_territory_area_positive'),
    sa.ForeignKeyConstraint(['boundary_version_id'], ['boundary_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['parent_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'boundary_version_id', name='uq_territory_code_version')
    )
    op.create_index(op.f('ix_territories_import_job_id'), 'territories', ['import_job_id'], unique=False)
    op.create_index('ix_territories_kato', 'territories', ['kato_code'], unique=False)
    op.create_index('ix_territories_level', 'territories', ['level'], unique=False)
    op.create_index(op.f('ix_territories_natural_key'), 'territories', ['natural_key'], unique=False)
    op.create_index('ix_territories_parent', 'territories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_territories_source_dataset_id'), 'territories', ['source_dataset_id'], unique=False)
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('addr_norm', sa.String(length=512), nullable=False),
    sa.Column('kato_code', sa.String(length=9), nullable=True),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geocode_precision', sa.String(length=16), nullable=False),
    sa.Column('organization_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint("kato_code IS NULL OR kato_code ~ '^[0-9]{9}$'", name='ck_address_kato_format'),
    sa.CheckConstraint('lat IS NULL OR (lat >= 40.0 AND lat <= 56.0)', name='ck_address_lat_range'),
    sa.CheckConstraint('lon IS NULL OR (lon >= 46.0 AND lon <= 88.0)', name='ck_address_lon_range'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('addr_norm', name='uq_address_norm')
    )
    op.create_index(op.f('ix_addresses_import_job_id'), 'addresses', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_addresses_natural_key'), 'addresses', ['natural_key'], unique=False)
    op.create_index(op.f('ix_addresses_source_dataset_id'), 'addresses', ['source_dataset_id'], unique=False)
    op.create_index('ix_addresses_territory', 'addresses', ['territory_id'], unique=False)
    op.create_table('budget_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('source_territory_code', sa.String(length=16), nullable=False),
    sa.Column('source_region_name', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('utv', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('utch', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('plg', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('plgp', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('plgo', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('sumrg', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('obz', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('obzsumrg', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('plgpsumrg', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('plgsumrg', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('source_row_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('period_month BETWEEN 1 AND 12', name='ck_budget_fact_month_range'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['program_id'], ['budget_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'source_territory_code', 'period_year', 'period_month', name='uq_budget_fact_program_territory_period')
    )
    op.create_index(op.f('ix_budget_facts_import_job_id'), 'budget_facts', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_budget_facts_natural_key'), 'budget_facts', ['natural_key'], unique=False)
    op.create_index('ix_budget_facts_period', 'budget_facts', ['period_year', 'period_month'], unique=False)
    op.create_index(op.f('ix_budget_facts_source_dataset_id'), 'budget_facts', ['source_dataset_id'], unique=False)
    op.create_index('ix_budget_facts_territory_period', 'budget_facts', ['territory_id', 'period_year', 'period_month'], unique=False)
    op.create_table('budget_monthly_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('source_territory_code', sa.String(length=16), nullable=False),
    sa.Column('source_region_name', sa.String(length=255), nullable=False),
    sa.Column('territory_name_normalized', sa.String(length=255), nullable=False),
    sa.Column('geo_level', sa.String(length=16), nullable=False),
    sa.Column('parent_territory_code', sa.String(length=16), nullable=True),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('r01_revenue_execution', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r02_expense_execution', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r04_revision_intensity', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r05_profile_error', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r06_balance_deviation', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r07_cash_buffer_months', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r09_absorption_pressure', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r10_commitment_lag', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r11_unpaid_commitments', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r12_underexecution_width', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r13_expense_hhi', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r14_financial_ops_deviation', sa.Numeric(precision=18, scale=9), nullable=False),
    sa.Column('r15_quality_flags', sa.Integer(), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=20, scale=3), nullable=False),
    sa.Column('model_code', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=18, scale=9), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('rank_in_month', sa.Integer(), nullable=True),
    sa.Column('data_completeness', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('indicator_completeness', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('override_triggered', sa.Boolean(), nullable=False),
    sa.Column('missing_roots_flag', sa.Boolean(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_ru', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('data_completeness >= 0 AND data_completeness <= 1', name='ck_budget_metric_completeness_range'),
    sa.CheckConstraint('period_month BETWEEN 1 AND 12', name='ck_budget_metric_month_range'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_budget_metric_score_range'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_territory_code', 'period_year', 'period_month', 'model_version', name='uq_budget_metric_territory_period_version')
    )
    op.create_index('ix_budget_metrics_level', 'budget_monthly_metrics', ['risk_level'], unique=False)
    op.create_index('ix_budget_metrics_period', 'budget_monthly_metrics', ['period_year', 'period_month'], unique=False)
    op.create_index('ix_budget_metrics_territory', 'budget_monthly_metrics', ['territory_id'], unique=False)
    op.create_index(op.f('ix_budget_monthly_metrics_import_job_id'), 'budget_monthly_metrics', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_budget_monthly_metrics_natural_key'), 'budget_monthly_metrics', ['natural_key'], unique=False)
    op.create_index(op.f('ix_budget_monthly_metrics_source_dataset_id'), 'budget_monthly_metrics', ['source_dataset_id'], unique=False)
    op.create_table('population_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('male', sa.Integer(), nullable=True),
    sa.Column('female', sa.Integer(), nullable=True),
    sa.Column('urban_total', sa.Integer(), nullable=True),
    sa.Column('urban_male', sa.Integer(), nullable=True),
    sa.Column('urban_female', sa.Integer(), nullable=True),
    sa.Column('rural_total', sa.Integer(), nullable=True),
    sa.Column('rural_male', sa.Integer(), nullable=True),
    sa.Column('rural_female', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('total >= 0', name='ck_population_total_non_negative'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('territory_id', 'as_of_date', name='uq_population_territory_date')
    )
    op.create_index(op.f('ix_population_stats_import_job_id'), 'population_stats', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_population_stats_natural_key'), 'population_stats', ['natural_key'], unique=False)
    op.create_index(op.f('ix_population_stats_source_dataset_id'), 'population_stats', ['source_dataset_id'], unique=False)
    op.create_table('procurement_customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_truncated', sa.String(length=64), nullable=True),
    sa.Column('bin', sa.String(length=12), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('bin IS NULL OR length(bin) = 12', name='ck_customer_bin_length'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_customer_name')
    )
    op.create_index('ix_customers_bin', 'procurement_customers', ['bin'], unique=False)
    op.create_index(op.f('ix_procurement_customers_import_job_id'), 'procurement_customers', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_procurement_customers_natural_key'), 'procurement_customers', ['natural_key'], unique=False)
    op.create_index(op.f('ix_procurement_customers_source_dataset_id'), 'procurement_customers', ['source_dataset_id'], unique=False)
    op.create_table('project_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('territory_raw', sa.Text(), nullable=True),
    sa.Column('territory_precision', sa.String(length=16), nullable=False),
    sa.Column('has_data_error', sa.Boolean(), nullable=False),
    sa.Column('data_error_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('risk_model_code', sa.String(length=32), nullable=True),
    sa.Column('risk_model_version', sa.String(length=16), nullable=True),
    sa.Column('risk_raw_score', sa.Float(), nullable=True),
    sa.Column('risk_available_weight', sa.Float(), nullable=True),
    sa.Column('risk_normalized_score', sa.Float(), nullable=True),
    sa.Column('risk_significance_k', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_completeness', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('risk_is_preliminary', sa.Boolean(), nullable=False),
    sa.Column('risk_override_applied', sa.String(length=255), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("kind <> 'ppp_project' OR territory_precision = 'region'", name='ck_ppp_project_territory_is_region'),
    sa.CheckConstraint('risk_completeness IS NULL OR (risk_completeness >= 0 AND risk_completeness <= 1)', name='ck_project_entity_completeness_range'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_project_entity_score_range'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_entities_import_job_id'), 'project_entities', ['import_job_id'], unique=False)
    op.create_index('ix_project_entities_kind', 'project_entities', ['kind'], unique=False)
    op.create_index(op.f('ix_project_entities_natural_key'), 'project_entities', ['natural_key'], unique=False)
    op.create_index('ix_project_entities_risk_level', 'project_entities', ['risk_level'], unique=False)
    op.create_index(op.f('ix_project_entities_source_dataset_id'), 'project_entities', ['source_dataset_id'], unique=False)
    op.create_index('ix_project_entities_territory', 'project_entities', ['territory_id'], unique=False)
    op.create_table('subsidy_recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('xin', sa.String(length=12), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('director_name', sa.String(length=255), nullable=True),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('territory_name_raw', sa.String(length=255), nullable=True),
    sa.Column('territory_resolution', sa.String(length=24), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payments_count', sa.Integer(), nullable=False),
    sa.Column('programs_count', sa.Integer(), nullable=False),
    sa.Column('animal_types_count', sa.Integer(), nullable=True),
    sa.Column('district_share', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('oblast_share', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('affiliated_count', sa.Integer(), nullable=True),
    sa.Column('anomalous_payment_share', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('amount_outlier_share', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('s1_concentration', sa.Float(), nullable=True),
    sa.Column('s2_repetition', sa.Float(), nullable=True),
    sa.Column('s3_affiliation', sa.Float(), nullable=True),
    sa.Column('s4_process_anomaly', sa.Float(), nullable=True),
    sa.Column('s5_amount_outlier', sa.Float(), nullable=True),
    sa.Column('model_code', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('risk_completeness', sa.Float(), nullable=False),
    sa.Column('risk_exposure', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('book_risk_score', sa.Float(), nullable=True),
    sa.Column('book_risk_level', sa.String(length=16), nullable=True),
    sa.Column('book_risk_exposure', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('book_rank', sa.Integer(), nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('char_length(xin) = 12', name='ck_subsidy_recipient_xin_len'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_subsidy_recipient_score_range'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xin', 'data_version', name='uq_subsidy_recipient_xin_version')
    )
    op.create_index(op.f('ix_subsidy_recipients_import_job_id'), 'subsidy_recipients', ['import_job_id'], unique=False)
    op.create_index('ix_subsidy_recipients_level', 'subsidy_recipients', ['risk_level'], unique=False)
    op.create_index(op.f('ix_subsidy_recipients_natural_key'), 'subsidy_recipients', ['natural_key'], unique=False)
    op.create_index(op.f('ix_subsidy_recipients_source_dataset_id'), 'subsidy_recipients', ['source_dataset_id'], unique=False)
    op.create_index('ix_subsidy_recipients_territory', 'subsidy_recipients', ['territory_id'], unique=False)
    op.create_index('ix_subsidy_recipients_xin', 'subsidy_recipients', ['xin'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('in_rnu_gz', sa.Boolean(), nullable=False),
    sa.Column('in_lzhepred_list', sa.Boolean(), nullable=False),
    sa.Column('no_physical_activity', sa.Boolean(), nullable=False),
    sa.Column('high_oked_diversity', sa.Boolean(), nullable=False),
    sa.Column('mass_address', sa.Boolean(), nullable=False),
    sa.Column('nominal_director', sa.Boolean(), nullable=False),
    sa.Column('n_contracts', sa.Integer(), nullable=True),
    sa.Column('max_direct_one_customer', sa.Integer(), nullable=True),
    sa.Column('pct_terminated', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('layer_8_7_points', sa.Integer(), nullable=True),
    sa.Column('layer_8_7_level', sa.String(length=24), nullable=True),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('legal_address_raw', sa.Text(), nullable=True),
    sa.Column('region_source_name', sa.String(length=255), nullable=True),
    sa.Column('district_source_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('length(bin) = 12', name='ck_supplier_bin_length'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bin', name='uq_supplier_bin')
    )
    op.create_index('ix_suppliers_category_a', 'suppliers', ['in_rnu_gz', 'in_lzhepred_list'], unique=False)
    op.create_index(op.f('ix_suppliers_import_job_id'), 'suppliers', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_suppliers_natural_key'), 'suppliers', ['natural_key'], unique=False)
    op.create_index(op.f('ix_suppliers_source_dataset_id'), 'suppliers', ['source_dataset_id'], unique=False)
    op.create_index('ix_suppliers_territory', 'suppliers', ['territory_id'], unique=False)
    op.create_table('territory_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('normalized', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('source_layer', sa.String(length=64), nullable=True),
    sa.Column('is_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized', 'territory_id', name='uq_alias_normalized_territory')
    )
    op.create_index('ix_territory_aliases_normalized', 'territory_aliases', ['normalized'], unique=False)
    op.create_table('territory_geometries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('geom_simplified_mid', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geom_simplified_low', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validity_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('territory_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login', name='uq_user_login')
    )
    op.create_index('ix_users_role', 'users', ['role_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('user_login', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_occurred', 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index('ix_audit_log_user_action', 'audit_log', ['user_id', 'action'], unique=False)
    op.create_table('construction_expertise_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registration_number', sa.String(length=6), nullable=False),
    sa.Column('registration_number_raw', sa.String(length=16), nullable=True),
    sa.Column('conclusion_number', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('object_identity_key', sa.String(length=512), nullable=True),
    sa.Column('customer_raw', sa.Text(), nullable=True),
    sa.Column('customer_key', sa.String(length=512), nullable=True),
    sa.Column('designer_raw', sa.Text(), nullable=True),
    sa.Column('designer_key', sa.String(length=512), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('work_kind', sa.String(length=255), nullable=True),
    sa.Column('design_stage', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=512), nullable=True),
    sa.Column('object_kind', sa.String(length=512), nullable=True),
    sa.Column('funding_source', sa.String(length=255), nullable=True),
    sa.Column('expertise_place', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=64), nullable=True),
    sa.Column('capacity_unit', sa.String(length=64), nullable=True),
    sa.Column('author_supervision_status', sa.String(length=128), nullable=True),
    sa.Column('has_cost_estimate', sa.Boolean(), nullable=True),
    sa.Column('technological_complexity', sa.String(length=128), nullable=True),
    sa.Column('responsibility_level', sa.String(length=128), nullable=True),
    sa.Column('hazard_class', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('efficiency_class', sa.String(length=64), nullable=True),
    sa.Column('full_set_cost', sa.String(length=64), nullable=True),
    sa.Column('b1_design_correction', sa.Float(), nullable=True),
    sa.Column('b2_repeated_expertise', sa.Float(), nullable=True),
    sa.Column('b3_author_supervision', sa.Float(), nullable=True),
    sa.Column('b4_no_cost_estimate', sa.Float(), nullable=True),
    sa.Column('b5_designer_concentration', sa.Float(), nullable=True),
    sa.Column('b6_customer_correction_share', sa.Float(), nullable=True),
    sa.Column('significance_hazard_class', sa.Boolean(), nullable=True),
    sa.Column('significance_responsibility', sa.Boolean(), nullable=True),
    sa.CheckConstraint("registration_number ~ '^[0-9]{6}$'", name='ck_expertise_registration_six_digits'),
    sa.ForeignKeyConstraint(['id'], ['project_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number', name='uq_expertise_registration_number')
    )
    op.create_index('ix_expertise_customer_key', 'construction_expertise_objects', ['customer_key'], unique=False)
    op.create_index('ix_expertise_designer_key', 'construction_expertise_objects', ['designer_key'], unique=False)
    op.create_index('ix_expertise_object_identity', 'construction_expertise_objects', ['object_identity_key'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('territory_status', sa.String(length=24), nullable=False),
    sa.Column('oked_main', sa.String(length=5), nullable=True),
    sa.Column('oked_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('krp_code', sa.Integer(), nullable=True),
    sa.Column('employees_count', sa.Integer(), nullable=True),
    sa.Column('tax_paid_total', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('tax_burden_ratio', sa.Float(), nullable=True),
    sa.Column('vat_registered', sa.Boolean(), nullable=True),
    sa.Column('licenses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('address_company_count', sa.Integer(), nullable=True),
    sa.Column('director_company_count', sa.Integer(), nullable=True),
    sa.Column('oked_sections_count', sa.Integer(), nullable=True),
    sa.Column('no_physical_activity', sa.Boolean(), nullable=True),
    sa.Column('inactive_kkm_only', sa.Boolean(), nullable=True),
    sa.Column('in_rnu_gz', sa.Boolean(), nullable=True),
    sa.Column('rnu_start_date', sa.Date(), nullable=True),
    sa.Column('rnu_end_date', sa.Date(), nullable=True),
    sa.Column('in_rnu_quasi', sa.Boolean(), nullable=True),
    sa.Column('in_lzhepred_list', sa.Boolean(), nullable=True),
    sa.Column('director_in_lzhepred', sa.Boolean(), nullable=True),
    sa.Column('kgd_unreliable_lists', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_category_a', sa.Boolean(), nullable=False),
    sa.Column('category_a_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_model_code', sa.String(length=32), nullable=True),
    sa.Column('risk_model_version', sa.String(length=16), nullable=True),
    sa.Column('risk_raw_score', sa.Float(), nullable=True),
    sa.Column('risk_available_weight', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_completeness', sa.Float(), nullable=True),
    sa.Column('risk_level_preliminary', sa.String(length=16), nullable=True),
    sa.Column('risk_level_strict', sa.String(length=16), nullable=True),
    sa.Column('risk_is_preliminary', sa.Boolean(), nullable=False),
    sa.Column('risk_override_applied', sa.String(length=255), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint("bin ~ '^[0-9]{12}$'", name='ck_organization_bin_format'),
    sa.CheckConstraint('risk_completeness IS NULL OR (risk_completeness >= 0 AND risk_completeness <= 1)', name='ck_organization_completeness_range'),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_organization_score_range'),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bin', name='uq_organization_bin')
    )
    op.create_index('ix_organizations_address', 'organizations', ['address_id'], unique=False)
    op.create_index('ix_organizations_category_a', 'organizations', ['is_category_a'], unique=False)
    op.create_index(op.f('ix_organizations_import_job_id'), 'organizations', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_organizations_natural_key'), 'organizations', ['natural_key'], unique=False)
    op.create_index('ix_organizations_risk_level_strict', 'organizations', ['risk_level_strict'], unique=False)
    op.create_index(op.f('ix_organizations_source_dataset_id'), 'organizations', ['source_dataset_id'], unique=False)
    op.create_table('ppp_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registry_number', sa.Integer(), nullable=False),
    sa.Column('region_raw', sa.Text(), nullable=True),
    sa.Column('project_level', sa.String(length=32), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('object_kind', sa.String(length=255), nullable=True),
    sa.Column('status_raw', sa.String(length=255), nullable=True),
    sa.Column('is_terminated', sa.Boolean(), nullable=False),
    sa.Column('initiative_kind', sa.String(length=128), nullable=True),
    sa.Column('contract_kind', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=255), nullable=True),
    sa.Column('private_partner_raw', sa.Text(), nullable=True),
    sa.Column('private_partner_key', sa.String(length=255), nullable=True),
    sa.Column('government_partner_raw', sa.Text(), nullable=True),
    sa.Column('government_partner_key', sa.String(length=255), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('construction_start', sa.Date(), nullable=True),
    sa.Column('construction_end', sa.Date(), nullable=True),
    sa.Column('operation_start', sa.Date(), nullable=True),
    sa.Column('operation_end', sa.Date(), nullable=True),
    sa.Column('cost_initial', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('investments', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('government_participation_form', sa.Text(), nullable=True),
    sa.Column('contest_number', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('a1_terminated', sa.Float(), nullable=True),
    sa.Column('a2_partner_termination_history', sa.Float(), nullable=True),
    sa.Column('a3_partner_region_concentration', sa.Float(), nullable=True),
    sa.Column('a4_gov_partner_concentration', sa.Float(), nullable=True),
    sa.Column('a5_construction_overdue', sa.Float(), nullable=True),
    sa.Column('a6_investment_growth', sa.Float(), nullable=True),
    sa.Column('a7_non_competitive', sa.Float(), nullable=True),
    sa.Column('significance_top_quartile_cost', sa.Boolean(), nullable=True),
    sa.Column('significance_republican', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['project_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry_number', name='uq_ppp_project_registry_number')
    )
    op.create_index('ix_ppp_projects_contest_number', 'ppp_projects', ['contest_number'], unique=False)
    op.create_index('ix_ppp_projects_government_partner_key', 'ppp_projects', ['government_partner_key'], unique=False)
    op.create_index('ix_ppp_projects_private_partner_key', 'ppp_projects', ['private_partner_key'], unique=False)
    op.create_table('procurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.String(length=32), nullable=False),
    sa.Column('announcement_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('submitted_bids', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['procurement_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_number', name='uq_procurement_announcement_number')
    )
    op.create_index('ix_procurements_announcement_id', 'procurements', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_procurements_import_job_id'), 'procurements', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_procurements_natural_key'), 'procurements', ['natural_key'], unique=False)
    op.create_index(op.f('ix_procurements_source_dataset_id'), 'procurements', ['source_dataset_id'], unique=False)
    op.create_table('project_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_entity_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name_raw', sa.Text(), nullable=False),
    sa.Column('name_key', sa.String(length=512), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=True),
    sa.Column('bin_source', sa.String(length=64), nullable=True),
    sa.Column('is_consortium_member', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint("bin IS NULL OR bin ~ '^[0-9]{12}$'", name='ck_participant_bin_format'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_entity_id'], ['project_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_participants_bin', 'project_participants', ['bin'], unique=False)
    op.create_index('ix_project_participants_entity_role', 'project_participants', ['project_entity_id', 'role'], unique=False)
    op.create_index(op.f('ix_project_participants_import_job_id'), 'project_participants', ['import_job_id'], unique=False)
    op.create_index('ix_project_participants_name_key', 'project_participants', ['name_key'], unique=False)
    op.create_index(op.f('ix_project_participants_natural_key'), 'project_participants', ['natural_key'], unique=False)
    op.create_index(op.f('ix_project_participants_source_dataset_id'), 'project_participants', ['source_dataset_id'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_saved_view_owner_name')
    )
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('normalized_name', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uq_source_file_sha256')
    )
    op.create_table('subsidy_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('territory_name_raw', sa.String(length=255), nullable=True),
    sa.Column('bid_number', sa.String(length=32), nullable=False),
    sa.Column('bid_status', sa.String(length=64), nullable=True),
    sa.Column('animal_type', sa.String(length=128), nullable=True),
    sa.Column('positive_decision_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('local_payment_at', sa.DateTime(), nullable=True),
    sa.Column('republic_payment_at', sa.DateTime(), nullable=True),
    sa.Column('subsidies_norm', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_local', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_republic', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_owed', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('decision_to_payment_days', sa.Integer(), nullable=True),
    sa.Column('flag_paid_before_decision', sa.Boolean(), nullable=False),
    sa.Column('flag_abnormal_lag', sa.Boolean(), nullable=False),
    sa.Column('flag_amount_outlier', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('amount_total >= 0', name='ck_subsidy_payment_amount_non_negative'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['program_id'], ['subsidy_programs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['subsidy_recipients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bid_number', 'data_version', name='uq_subsidy_payment_bid_version')
    )
    op.create_index(op.f('ix_subsidy_payments_import_job_id'), 'subsidy_payments', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_subsidy_payments_natural_key'), 'subsidy_payments', ['natural_key'], unique=False)
    op.create_index('ix_subsidy_payments_program', 'subsidy_payments', ['program_id'], unique=False)
    op.create_index('ix_subsidy_payments_recipient', 'subsidy_payments', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_subsidy_payments_source_dataset_id'), 'subsidy_payments', ['source_dataset_id'], unique=False)
    op.create_index('ix_subsidy_payments_territory', 'subsidy_payments', ['territory_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('procurement_id', sa.UUID(), nullable=True),
    sa.Column('brief_content_ru', sa.Text(), nullable=True),
    sa.Column('subject_type', sa.String(length=32), nullable=True),
    sa.Column('planned_method', sa.Text(), nullable=True),
    sa.Column('actual_method', sa.Text(), nullable=True),
    sa.Column('planned_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('final_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('planned_exec_date', sa.Date(), nullable=True),
    sa.Column('actual_exec_date', sa.Date(), nullable=True),
    sa.Column('contract_status', sa.String(length=64), nullable=True),
    sa.Column('is_terminated', sa.Boolean(), nullable=False),
    sa.Column('territory_id', sa.UUID(), nullable=True),
    sa.Column('region_source_name', sa.String(length=255), nullable=True),
    sa.Column('district_source_name', sa.String(length=255), nullable=True),
    sa.Column('model_code', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=16), nullable=False),
    sa.Column('s_raw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('w_avail', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('s_norm', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('significance_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('completeness', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('is_preliminary', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=255), nullable=True),
    sa.Column('indicator_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation_ru', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)', name='ck_contract_score_range'),
    sa.CheckConstraint('significance_multiplier IS NULL OR (significance_multiplier >= 1 AND significance_multiplier <= 1.3)', name='ck_contract_k_range'),
    sa.CheckConstraint('w_avail IS NULL OR (w_avail >= 0 AND w_avail <= 100)', name='ck_contract_w_avail_range'),
    sa.ForeignKeyConstraint(['customer_id'], ['procurement_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', name='uq_contract_source_id')
    )
    op.create_index('ix_contracts_customer', 'contracts', ['customer_id'], unique=False)
    op.create_index('ix_contracts_district', 'contracts', ['district_source_name'], unique=False)
    op.create_index(op.f('ix_contracts_import_job_id'), 'contracts', ['import_job_id'], unique=False)
    op.create_index('ix_contracts_level', 'contracts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_contracts_natural_key'), 'contracts', ['natural_key'], unique=False)
    op.create_index(op.f('ix_contracts_source_dataset_id'), 'contracts', ['source_dataset_id'], unique=False)
    op.create_index('ix_contracts_supplier', 'contracts', ['supplier_id'], unique=False)
    op.create_table('identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('raw_value', sa.String(length=64), nullable=False),
    sa.Column('normalized_value', sa.String(length=64), nullable=False),
    sa.Column('leading_zeros_restored', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('organization_id IS NOT NULL OR person_id IS NOT NULL', name='ck_identifier_has_owner'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'normalized_value', 'organization_id', name='uq_identifier_value')
    )
    op.create_index(op.f('ix_identifiers_import_job_id'), 'identifiers', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_identifiers_natural_key'), 'identifiers', ['natural_key'], unique=False)
    op.create_index('ix_identifiers_normalized', 'identifiers', ['kind', 'normalized_value'], unique=False)
    op.create_index(op.f('ix_identifiers_source_dataset_id'), 'identifiers', ['source_dataset_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('layer_code', sa.String(length=16), nullable=True),
    sa.Column('importer', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_dry_run', sa.Boolean(), nullable=False),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_created', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('territory_match_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reconciliation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_by_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_jobs_status_started', 'import_jobs', ['status', 'started_at'], unique=False)
    op.create_table('organization_person_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('share_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.CheckConstraint('share_percent IS NULL OR (share_percent >= 0 AND share_percent <= 100)', name='ck_org_person_share_range'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'person_id', 'role', 'valid_from', name='uq_org_person_role_period')
    )
    op.create_index('ix_org_person_roles_person', 'organization_person_roles', ['person_id'], unique=False)
    op.create_index(op.f('ix_organization_person_roles_import_job_id'), 'organization_person_roles', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_organization_person_roles_natural_key'), 'organization_person_roles', ['natural_key'], unique=False)
    op.create_index(op.f('ix_organization_person_roles_source_dataset_id'), 'organization_person_roles', ['source_dataset_id'], unique=False)
    op.create_table('procurement_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('procurement_id', sa.UUID(), nullable=False),
    sa.Column('lot_id', sa.String(length=32), nullable=True),
    sa.Column('lot_number', sa.String(length=64), nullable=True),
    sa.Column('lot_name', sa.Text(), nullable=True),
    sa.Column('lot_status', sa.String(length=64), nullable=True),
    sa.Column('tru_code', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('planned_sum', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('delivery_kato', sa.String(length=9), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procurement_id', 'lot_number', name='uq_lot_procurement_number')
    )
    op.create_index('ix_lots_delivery_kato', 'procurement_lots', ['delivery_kato'], unique=False)
    op.create_index(op.f('ix_procurement_lots_import_job_id'), 'procurement_lots', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_procurement_lots_natural_key'), 'procurement_lots', ['natural_key'], unique=False)
    op.create_index(op.f('ix_procurement_lots_source_dataset_id'), 'procurement_lots', ['source_dataset_id'], unique=False)
    op.create_table('source_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('layer_code', sa.String(length=16), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=True),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('columns_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'sheet_name', name='uq_dataset_file_sheet')
    )
    op.create_table('contract_additions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('conclusion_date', sa.Date(), nullable=True),
    sa.Column('planned_exec_date', sa.Date(), nullable=True),
    sa.Column('final_total_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('actual_total_amount', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('changes_term', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_dataset_id', sa.UUID(), nullable=True),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('natural_key', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_as_of', sa.Date(), nullable=True),
    sa.Column('validation_status', sa.String(length=24), nullable=False),
    sa.Column('validation_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['source_dataset_id'], ['source_datasets.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_additions_contract', 'contract_additions', ['contract_id'], unique=False)
    op.create_index('ix_contract_additions_creation', 'contract_additions', ['creation_date'], unique=False)
    op.create_index(op.f('ix_contract_additions_import_job_id'), 'contract_additions', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_contract_additions_natural_key'), 'contract_additions', ['natural_key'], unique=False)
    op.create_index(op.f('ix_contract_additions_source_dataset_id'), 'contract_additions', ['source_dataset_id'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_job_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_row_ref', sa.String(length=255), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dq_issues_code', 'data_quality_issues', ['code'], unique=False)
    op.create_index('ix_dq_issues_job_severity', 'data_quality_issues', ['import_job_id', 'severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dq_issues_job_severity', table_name='data_quality_issues')
    op.drop_index('ix_dq_issues_code', table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_contract_additions_source_dataset_id'), table_name='contract_additions')
    op.drop_index(op.f('ix_contract_additions_natural_key'), table_name='contract_additions')
    op.drop_index(op.f('ix_contract_additions_import_job_id'), table_name='contract_additions')
    op.drop_index('ix_contract_additions_creation', table_name='contract_additions')
    op.drop_index('ix_contract_additions_contract', table_name='contract_additions')
    op.drop_table('contract_additions')
    op.drop_table('source_datasets')
    op.drop_index(op.f('ix_procurement_lots_source_dataset_id'), table_name='procurement_lots')
    op.drop_index(op.f('ix_procurement_lots_natural_key'), table_name='procurement_lots')
    op.drop_index(op.f('ix_procurement_lots_import_job_id'), table_name='procurement_lots')
    op.drop_index('ix_lots_delivery_kato', table_name='procurement_lots')
    op.drop_table('procurement_lots')
    op.drop_index(op.f('ix_organization_person_roles_source_dataset_id'), table_name='organization_person_roles')
    op.drop_index(op.f('ix_organization_person_roles_natural_key'), table_name='organization_person_roles')
    op.drop_index(op.f('ix_organization_person_roles_import_job_id'), table_name='organization_person_roles')
    op.drop_index('ix_org_person_roles_person', table_name='organization_person_roles')
    op.drop_table('organization_person_roles')
    op.drop_index('ix_import_jobs_status_started', table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_identifiers_source_dataset_id'), table_name='identifiers')
    op.drop_index('ix_identifiers_normalized', table_name='identifiers')
    op.drop_index(op.f('ix_identifiers_natural_key'), table_name='identifiers')
    op.drop_index(op.f('ix_identifiers_import_job_id'), table_name='identifiers')
    op.drop_table('identifiers')
    op.drop_index('ix_contracts_supplier', table_name='contracts')
    op.drop_index(op.f('ix_contracts_source_dataset_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_natural_key'), table_name='contracts')
    op.drop_index('ix_contracts_level', table_name='contracts')
    op.drop_index(op.f('ix_contracts_import_job_id'), table_name='contracts')
    op.drop_index('ix_contracts_district', table_name='contracts')
    op.drop_index('ix_contracts_customer', table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_subsidy_payments_territory', table_name='subsidy_payments')
    op.drop_index(op.f('ix_subsidy_payments_source_dataset_id'), table_name='subsidy_payments')
    op.drop_index('ix_subsidy_payments_recipient', table_name='subsidy_payments')
    op.drop_index('ix_subsidy_payments_program', table_name='subsidy_payments')
    op.drop_index(op.f('ix_subsidy_payments_natural_key'), table_name='subsidy_payments')
    op.drop_index(op.f('ix_subsidy_payments_import_job_id'), table_name='subsidy_payments')
    op.drop_table('subsidy_payments')
    op.drop_table('source_files')
    op.drop_table('saved_views')
    op.drop_index(op.f('ix_project_participants_source_dataset_id'), table_name='project_participants')
    op.drop_index(op.f('ix_project_participants_natural_key'), table_name='project_participants')
    op.drop_index('ix_project_participants_name_key', table_name='project_participants')
    op.drop_index(op.f('ix_project_participants_import_job_id'), table_name='project_participants')
    op.drop_index('ix_project_participants_entity_role', table_name='project_participants')
    op.drop_index('ix_project_participants_bin', table_name='project_participants')
    op.drop_table('project_participants')
    op.drop_index(op.f('ix_procurements_source_dataset_id'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_natural_key'), table_name='procurements')
    op.drop_index(op.f('ix_procurements_import_job_id'), table_name='procurements')
    op.drop_index('ix_procurements_announcement_id', table_name='procurements')
    op.drop_table('procurements')
    op.drop_index('ix_ppp_projects_private_partner_key', table_name='ppp_projects')
    op.drop_index('ix_ppp_projects_government_partner_key', table_name='ppp_projects')
    op.drop_index('ix_ppp_projects_contest_number', table_name='ppp_projects')
    op.drop_table('ppp_projects')
    op.drop_index(op.f('ix_organizations_source_dataset_id'), table_name='organizations')
    op.drop_index('ix_organizations_risk_level_strict', table_name='organizations')
    op.drop_index(op.f('ix_organizations_natural_key'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_import_job_id'), table_name='organizations')
    op.drop_index('ix_organizations_category_a', table_name='organizations')
    op.drop_index('ix_organizations_address', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_expertise_object_identity', table_name='construction_expertise_objects')
    op.drop_index('ix_expertise_designer_key', table_name='construction_expertise_objects')
    op.drop_index('ix_expertise_customer_key', table_name='construction_expertise_objects')
    op.drop_table('construction_expertise_objects')
    op.drop_index('ix_audit_log_user_action', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index('ix_audit_log_occurred', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('territory_geometries')
    op.drop_index('ix_territory_aliases_normalized', table_name='territory_aliases')
    op.drop_table('territory_aliases')
    op.drop_index('ix_suppliers_territory', table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_source_dataset_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_natural_key'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_import_job_id'), table_name='suppliers')
    op.drop_index('ix_suppliers_category_a', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('ix_subsidy_recipients_xin', table_name='subsidy_recipients')
    op.drop_index('ix_subsidy_recipients_territory', table_name='subsidy_recipients')
    op.drop_index(op.f('ix_subsidy_recipients_source_dataset_id'), table_name='subsidy_recipients')
    op.drop_index(op.f('ix_subsidy_recipients_natural_key'), table_name='subsidy_recipients')
    op.drop_index('ix_subsidy_recipients_level', table_name='subsidy_recipients')
    op.drop_index(op.f('ix_subsidy_recipients_import_job_id'), table_name='subsidy_recipients')
    op.drop_table('subsidy_recipients')
    op.drop_index('ix_project_entities_territory', table_name='project_entities')
    op.drop_index(op.f('ix_project_entities_source_dataset_id'), table_name='project_entities')
    op.drop_index('ix_project_entities_risk_level', table_name='project_entities')
    op.drop_index(op.f('ix_project_entities_natural_key'), table_name='project_entities')
    op.drop_index('ix_project_entities_kind', table_name='project_entities')
    op.drop_index(op.f('ix_project_entities_import_job_id'), table_name='project_entities')
    op.drop_table('project_entities')
    op.drop_index(op.f('ix_procurement_customers_source_dataset_id'), table_name='procurement_customers')
    op.drop_index(op.f('ix_procurement_customers_natural_key'), table_name='procurement_customers')
    op.drop_index(op.f('ix_procurement_customers_import_job_id'), table_name='procurement_customers')
    op.drop_index('ix_customers_bin', table_name='procurement_customers')
    op.drop_table('procurement_customers')
    op.drop_index(op.f('ix_population_stats_source_dataset_id'), table_name='population_stats')
    op.drop_index(op.f('ix_population_stats_natural_key'), table_name='population_stats')
    op.drop_index(op.f('ix_population_stats_import_job_id'), table_name='population_stats')
    op.drop_table('population_stats')
    op.drop_index(op.f('ix_budget_monthly_metrics_source_dataset_id'), table_name='budget_monthly_metrics')
    op.drop_index(op.f('ix_budget_monthly_metrics_natural_key'), table_name='budget_monthly_metrics')
    op.drop_index(op.f('ix_budget_monthly_metrics_import_job_id'), table_name='budget_monthly_metrics')
    op.drop_index('ix_budget_metrics_territory', table_name='budget_monthly_metrics')
    op.drop_index('ix_budget_metrics_period', table_name='budget_monthly_metrics')
    op.drop_index('ix_budget_metrics_level', table_name='budget_monthly_metrics')
    op.drop_table('budget_monthly_metrics')
    op.drop_index('ix_budget_facts_territory_period', table_name='budget_facts')
    op.drop_index(op.f('ix_budget_facts_source_dataset_id'), table_name='budget_facts')
    op.drop_index('ix_budget_facts_period', table_name='budget_facts')
    op.drop_index(op.f('ix_budget_facts_natural_key'), table_name='budget_facts')
    op.drop_index(op.f('ix_budget_facts_import_job_id'), table_name='budget_facts')
    op.drop_table('budget_facts')
    op.drop_index('ix_addresses_territory', table_name='addresses')
    op.drop_index(op.f('ix_addresses_source_dataset_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_natural_key'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_import_job_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_territories_source_dataset_id'), table_name='territories')
    op.drop_index('ix_territories_parent', table_name='territories')
    op.drop_index(op.f('ix_territories_natural_key'), table_name='territories')
    op.drop_index('ix_territories_level', table_name='territories')
    op.drop_index('ix_territories_kato', table_name='territories')
    op.drop_index(op.f('ix_territories_import_job_id'), table_name='territories')
    op.drop_table('territories')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_subsidy_programs_source_dataset_id'), table_name='subsidy_programs')
    op.drop_index(op.f('ix_subsidy_programs_natural_key'), table_name='subsidy_programs')
    op.drop_index(op.f('ix_subsidy_programs_import_job_id'), table_name='subsidy_programs')
    op.drop_index('ix_subsidy_programs_animal_type', table_name='subsidy_programs')
    op.drop_table('subsidy_programs')
    op.drop_table('roles')
    op.drop_index(op.f('ix_persons_source_dataset_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_natural_key'), table_name='persons')
    op.drop_index(op.f('ix_persons_import_job_id'), table_name='persons')
    op.drop_index('ix_persons_full_name', table_name='persons')
    op.drop_table('persons')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_budget_programs_source_dataset_id'), table_name='budget_programs')
    op.drop_index('ix_budget_programs_parent', table_name='budget_programs')
    op.drop_index(op.f('ix_budget_programs_natural_key'), table_name='budget_programs')
    op.drop_index('ix_budget_programs_level', table_name='budget_programs')
    op.drop_index(op.f('ix_budget_programs_import_job_id'), table_name='budget_programs')
    op.drop_table('budget_programs')
    op.drop_table('boundary_versions')
    # ### end Alembic commands ###
