# Generated by Django 4.2.13 on 2026-07-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sphere', models.CharField(choices=[('construction', 'Строительство'), ('housing', 'ЖКХ'), ('roads', 'Дороги'), ('education', 'Образование'), ('healthcare', 'Здравоохранение'), ('agriculture', 'АПК'), ('social', 'Социальная сфера'), ('digitalization', 'Цифровизация')], max_length=30)),
                ('program_name', models.CharField(max_length=500)),
                ('program_code', models.CharField(blank=True, max_length=50)),
                ('administrator', models.CharField(blank=True, max_length=300)),
                ('allocated', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('remainder', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('execution_pct', models.FloatField(default=0)),
                ('financing_source', models.CharField(blank=True, max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='regions.district')),
            ],
            options={
                'ordering': ['year', 'sphere'],
                'indexes': [models.Index(fields=['district', 'year', 'sphere'], name='budget_budg_distric_f3b8a5_idx')],
            },
        ),
    ]
