# Generated by Django 4.2.13 on 2026-07-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('bin_iin', models.CharField(max_length=12, unique=True)),
                ('director', models.CharField(blank=True, max_length=300)),
                ('founder', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('okved', models.CharField(blank=True, max_length=50)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('tax_load', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('risk_transit', models.BooleanField(default=False)),
                ('risk_fictitious', models.BooleanField(default=False)),
                ('risk_nominal', models.BooleanField(default=False)),
                ('risk_affiliated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
