# Generated by Django 4.2.13 on 2026-07-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=500)),
                ('customer_bin', models.CharField(blank=True, max_length=12)),
                ('supplier_name', models.CharField(max_length=500)),
                ('supplier_bin', models.CharField(blank=True, max_length=12)),
                ('subject', models.TextField()),
                ('method', models.CharField(choices=[('one_source', 'Из одного источника'), ('tender', 'Конкурс'), ('price_request', 'Запрос ценовых предложений'), ('auction', 'Аукцион')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('completed', 'Исполнен'), ('delayed', 'Просрочен'), ('terminated', 'Расторгнут')], default='active', max_length=20)),
                ('amendments_count', models.IntegerField(default=0)),
                ('risk_single', models.BooleanField(default=False)),
                ('risk_overpriced', models.BooleanField(default=False)),
                ('risk_splitting', models.BooleanField(default=False)),
                ('risk_affiliation', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='regions.district')),
            ],
            options={
                'ordering': ['-year', '-amount'],
                'indexes': [models.Index(fields=['district', 'year'], name='procurement_distric_e89a8f_idx'), models.Index(fields=['supplier_bin'], name='procurement_supplie_316079_idx')],
            },
        ),
    ]
