# Generated by Django 4.2.13 on 2026-07-07 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('bin_iin', models.CharField(max_length=12)),
                ('program', models.CharField(max_length=300)),
                ('subsidy_type', models.CharField(choices=[('plant', 'Растениеводство'), ('animal', 'Животноводство'), ('equipment', 'Техника'), ('irrigation', 'Орошение'), ('other', 'Иное')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('year', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('related_project', models.CharField(blank=True, max_length=300)),
                ('bank', models.CharField(blank=True, max_length=200)),
                ('risk_concentration', models.BooleanField(default=False)),
                ('risk_repeat', models.BooleanField(default=False)),
                ('risk_affiliation', models.BooleanField(default=False)),
                ('risk_no_activity', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidies', to='regions.district')),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
